#Stage 1 - build process
FROM node:12.16.3-alpine3.11 AS build-deps

ARG PHRASE_ACCES_TOKEN
ARG PHRASE_PROJECT_ID


WORKDIR /usr/src/app

RUN echo "USING DEV FILE $PHRASE_PROJECT_ID"

COPY package.json plopfile.js styleguide.config.js codegen.yml tsconfig.json types.d.ts ./

COPY public ./public
COPY src ./src
COPY scripts ./scripts
COPY plop-templates ./plop-templates

RUN npm install
RUN echo "Oh dang look at that $PHRASE_PROJECT_ID"
RUN node ./scripts/get_translations.js --accessToken=$PHRASE_ACCES_TOKEN --projectID=$PHRASE_PROJECT_ID

COPY .env.develop .env

RUN npm run build

#Stage 2 - production image
FROM nginx:1.17.0-alpine

RUN apk update && apk add bash
COPY ./devops/docker/entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh

COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
# replace with custom one
COPY devops/docker/nginx.conf /etc/nginx/conf.d
EXPOSE 3000
ENTRYPOINT ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
