version: 2.1

# Define the jobs we want to run for this project
jobs:
  cypress:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    working_directory: ~/spa
    steps:
      - checkout
      - restore_cache:
          key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}'
      - run: cp .env.dist .env && cp .env.e2e.dist ./e2e/.env
      - run: npm install && cd e2e && npm install && cd ..
      - save_cache:
          key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}'
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run: npm run build:ci
#      - run: npm run e2e:ci:chrome
#      - run: npm run e2e:ci:firefox
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress
  cypress/chrome:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    working_directory: ~/spa
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run e2e:ci:chrome

# Orchestrate our job run sequence
workflows:
  build_and_test:
    only: 'pull requests'
    jobs:
      - cypress
      - cypress/chrome:
          requires:
            - cypress


