version: 2.1

only-working-branches: &only-working-branches
  branches:
    only:
      - /hotfix/UL(?:-.+)?$/
      - /features/UL(?:-.+)?$/
      - /bugfix/UL(?:-.+)?$/
# Define the jobs we want to run for this project
jobs:
  build-tests:
    resource_class: medium
    docker:
      - image: cypress/base:12
    steps:
      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
      - restore_cache:
          key: 'cache-{{ arch }}-{{ checksum "package.json" }}'
      - run: cp .env.dist .env && cp .env.e2e.dist ./e2e/.env
      - run: npm install && cd e2e && npm install && cd ..
      - save_cache:
          key: 'cache-{{ arch }}-{{ checksum "package.json" }}'
          paths:
            - ~/node_modules
            - ~/.npm
            - ~/.cache
            - ~/e2e/node_modules
            - ~/e2e/.npm
      - run: npm run build:ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress

  run-chrome:
    docker:
      - image: cypress/browsers:node12.19.0-chrome86-ff82
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run e2e:ci:chrome
  run-firefox:
    resource_class: medium
    docker:
      - image: cypress/browsers:node12.19.0-chrome86-ff82
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run e2e:ci:firefox
  lint-and-test:
    docker:
      - image: cimg/node:12.19.1
    steps:
      - checkout
      - restore_cache:
          key: 'cache-{{ arch }}-{{ checksum "package.json" }}'
      - run:
          command: cp .env.dist .env && npm install && node ./scripts/get_translations.js --accessToken=$PHRASE_ACCESS_TOKEN --projectID=$PHRASE_PROJECT_ID
          name: "Config and install"
      - run: npm run lint
      - run: npm run coverage
      - run: npm run build


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-tests:
          filters:
            branches:
              only:
                - /hotfix/UL(?:-.+)?$/
                - /feature/UL(?:-.+)?$/
                - /bugfix/UL(?:-.+)?$/
      - lint-and-test:
          filters:
            branches:
              only:
                - /hotfix/UL(?:-.+)?$/
                - /feature/UL(?:-.+)?$/
                - /bugfix/UL(?:-.+)?$/
      - run-chrome:
          requires:
            - build-tests
      - run-firefox:
          requires:
            - build-tests


