version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - checkout
      - run: npm install --save-dev cypress@4.0.2
      - run: cp .env.dist .env
      - run: npm install
      - run: npm run build:ci
      - run: cd e2e && npm install && cd ..
      - run: cp .env.e2e.dist ./e2e/.env
      - run: npm run e2e:ci:firefox
      - run: npm run e2e:ci:chrome
  

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build