version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - checkout
      - setup_remote_docker:
          dcoker_layer_caching: true
      - run: cp .env.dist .env && cp .env.e2e.dist ./e2e/.env
      - run: npm install && cd e2e && npm install && cd ..
      - run: npm run build:ci
      - run: npm run e2e:ci:chrome
      - run: npm run e2e:ci:firefox

  

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build