version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-tests:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - restore_cache:
          key: 'cache-{{ arch }}-{{ checksum "package.json" }}'
      - run: cp .env.dist .env && cp .env.e2e.dist ./e2e/.env
      - run: npm install && cd e2e && npm install && cd ..
      - save_cache:
          key: 'cache-{{ arch }}-{{ checksum "package.json" }}'
          paths:
            - ~/node_modules
            - ~/.npm
            - ~/.cache
            - ~/e2e/node_modules
            - ~/e2e/.npm
      - run: npm run build:ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress

  run-chrome:
    docker:
      - image: cypress/browsers:node12.19.0-chrome86-ff82
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run e2e:ci:chrome
  run-firefox:
    docker:
      - image: cypress/browsers:node12.19.0-chrome86-ff82
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run e2e:ci:firefox

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-tests
      - run-chrome:
          resource_class: medium+
          requires:
            - build-tests
      - run-firefox:
          resource_class: medium+
          requires:
            - build-tests


