version: 2.1

# Define the jobs we want to run for this project
jobs:
  cypressBuild:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    working_directory: ~/spa
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run: cp .env.dist .env && cp .env.e2e.dist ./e2e/.env
      - run: npm install && cd e2e && npm install && cd ..
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build:ci


  cypresTestFireFox:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    working_directory: ~/spa
    steps:
      - run: npm run e2e:ci:firefox
  cypresTestChrome:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    working_directory: ~/spa
    steps:
      - run: npm run e2e:ci:chrome


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - cypressBuild
      - cypresTestFireFox:
          requires:
            - cypressBuild
      - cypresTestChrome:
          requires:
            - cypressBuild
