version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-v1-{{ .Branch }}-
          - node-v1-
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - checkout
#      - run: npm install --save-dev cypress@6.0.0
      - run: cp .env.dist .env && cp .env.e2e.dist ./e2e/.env
      - run: npm install && cd e2e && npm install && cd ..
      - run: npm run build:ci
      - run: npm run e2e:ci:chrome
      - run: npm run e2e:ci:firefox

  

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build