version: 2.1

orbs:
  cypress: cypress-io/cypress

# Define the jobs we want to run for this project
jobs:
  cypress:
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
    working_directory: ~/spa
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run: cp .env.dist .env && cp .env.e2e.dist ./e2e/.env
      - run: npm install && cd e2e && npm install && cd ..
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build:ci
      - run: npm run e2e:ci:chrome
      - run: npm run e2e:ci:firefox


# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - cypress/install:
          build: npm run build:ci
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 3
          group: 3x
#  build_and_test:
#    jobs:
#      - cypress

