# REST - don't remove

input LoginInput {
  username: String!
  password: String!
}
type AuthResult {
  AccessToken: String!
  RefreshToken: String!
  IdToken: String!
}

type AuthenticationResult {
  AuthenticationResult: AuthResult!
}

type LoginResponse {
  AuthenticationResult: String!
}

input ForgotPasswordInput {
  username: String!
}

type ForgotPasswordResponse {
  error: String
  stack: String
}

input ResetPasswordInput {
  newPassword: String!
}

type ResetPasswordResponse {
  error: String
  stack: String
}

input VerifyUserInput {
  code: String
  username: String
}
# END REST


extend type Mutation {
  #REST don't remove
  login(input: LoginInput): String
  forgotPassword(input: ForgotPasswordInput): ForgotPasswordResponse
  resetPassword(input: ResetPasswordInput, token: String!): ResetPasswordResponse
  verifyUser(input: VerifyUserInput): String
  #END REST
}
