# REST - don't remove

input LoginInput {
  username: String!
  password: String!
}

input ForgotPasswordInput {
  username: String!
}

type ForgotPasswordResponse {
  error: String
  stack: String
}


type VerifyUserResponse {
  error: String
  status: String!
}

type AuthenticationResult {
  AccessToken: String!
  RefreshToken: String!
}

type LoginResponse {
  error: String
  AuthenticationResult: AuthenticationResult!
}


input ResetPasswordInput {
  password: String!
  username: String!
  code: String!
}

type ResetPasswordResponse {
  error: String
  stack: String
}

input VerifyUserInput {
  code: String
  username: String
}
# END REST


extend type Mutation {
  #REST don't remove
  login(input: LoginInput): LoginResponse
  forgotPassword(input: ForgotPasswordInput): ForgotPasswordResponse
  resetPassword(input: ResetPasswordInput): ResetPasswordResponse
  verifyUser(input: VerifyUserInput): VerifyUserResponse
  #END REST
}
