enum CalendarTypes {
  Meeting
  Appointment
  Birthday
  Travel
  Private
  Task
}

enum AppointmentRepeat {
    NoRepeat
    Daily
    WorkDays
    Weekly
    Monthly
    Hourly
    Yearly
}

type AppointmentLocation {
    id: ID!
    availablePlaces: Int
    name: String
    suggest: Boolean
}

enum AppointmentType {
    Aquisition
    SigningContract
    Openhouse
    Purchase
    Inspection
    PersonalShowing
}

type AppointmentTerm {
    from: Date
    to: Date
}

enum AppointmentMeetingType {
    ExternalAgreement
    Collegial
    CompleteArgeement
    RedirectAppointment
    FollowUpJob
}

enum AppointmentAddressType {
     LinkedPersonAddress
     NewAcquisitionAddress
}
