enum MaritalStatusType {
    Single,
    MarriedCommunityOfProperty,
    MarriedPrenuptialAgreements,
    RegisteredPartner,
    Unmarried,
    LivingTogether,
    Widow,
    Widower
}

type LinkedCrm {
  id: ID!
  firstName: String
  extraNames: String
  initials: String
  lastName: String
  email: String
  phoneNumber: String
  avatar: File
  isPassedAway: Boolean
  dateOfDeath: Date
}

type CrmContact {
    type: String!
    contact: LinkedCrm!
}

type CrmPartner {
  isDivorced: Boolean
  partner: LinkedCrm!
}

type CrmFamilyContacts {
  id: ID!
  maritalStatus: String @uuidOrEnum(enum: ["MaritalStatusType"])
  maritalStatusDate: Date
  maritalStatusInformation: String
  familyCompositionChildren: Int
  familyCompositionAdults: Int
  familyCompositionInformation: String
  partners: [CrmPartner!]
  contacts: [CrmContact!]
}

input UpdateCrmFamilyContactsInput {
  id: ID!
  maritalStatus: String @uuidOrEnum(enum: ["MaritalStatusType"])
  maritalStatusDate: Date
  maritalStatusInformation: String
  familyCompositionChildren: Int
  familyCompositionAdults: Int
  familyCompositionInformation: String
  partners: [CrmPartnerInput!]
  contacts: [CrmContactInput!]
}

input CrmContactInput {
  type: String!
  contactId: ID!
}

input CrmPartnerInput {
  id: ID!
  isDivorced: Boolean
  isPassedAway: Boolean
  dateOfDeath: Date
}

extend type Mutation {
  updateCrmFamilyContacts(input: UpdateCrmFamilyContactsInput!): CrmFamilyContacts @auth
}

extend type Query {
  getCrmFamilyContacts(id: ID!): CrmFamilyContacts @auth
}