enum CrmType {
  Relation,
  Business
}

enum PreferredLanguageType {
  Dutch,
  English,
  Polish,
  German,
  French,
  Italian,
  Spanish,
  Portuguese
}

enum PreferredTitlePrefixType {
  Dr,
  Mr,
  Ir,
  Ing,
  Drs
}

enum PreferredTitleSuffixType {
  Msc,
  MA,
  MRE,
  MBA,
  Bc
}

enum PreferredLetterSalutationType {
  Family,
  Lord,
  Mylady,
  LordMylady
}

enum IdentificationType {
  Passport
  DriverLicense
  IdCard
  ResidencePermit
}

enum CrmStatus {
  ActionRequired,
  Active, Inactive
}

type CrmGeneral implements LastUpdated {
  id: ID!
  description: String
  firstName: String
  extraNames: String
  initials: String
  lastName: String
  avatar: File
  gender: GenderType
  dateOfBirth: Date
  placeOfBirth: String
  nationality: String
  dateOfDeath: Date
  isPassedAway: Boolean
  preferredLanguage: String @uuidOrEnum(enum: ["PreferredLanguageType"])
  identification: IdentificationType
  identificationNumber: String
  identificationIssueCity: String
  identificationIssueDate: Date
  identificationExpirationDate: Date
  preferredTitlePrefix: String @uuidOrEnum(enum: ["PreferredTitlePrefixType"])
  preferredTitleSuffix: String @uuidOrEnum(enum: ["PreferredTitleSuffixType"])
  preferredLetterSalutation: String @uuidOrEnum(enum: ["preferredLetterSalutationType"])
  preferredTitleInformation: String
  identificationNumbers: [CrmIdentificationNumber!]
  status: CrmStatus
  dateCreated: Date!
  lastEditedBy: LastUpdatedProfile
  dateUpdated: Date
  completeness: Float!
}

type CrmIdentificationNumber {
  type: IdentificationNumberType!
  number: String
  name: String
}

input CrmIdentificationNumberInput {
  type: IdentificationNumberType!
  number: String
  name: String
}

input CreateCrmInput {
  type: CrmType!
  firstName: String
  initials: String
  lastName: String
  email: String
  phoneNumber: String
}

input UpdateCrmGeneralInput {
  id: ID!
  description: String
  firstName: String
  extraNames: String
  initials: String
  lastName: String
  gender: GenderType
  avatarId: String,
  dateOfBirth: Date
  placeOfBirth: String
  nationality: String
  dateOfDeath: Date
  isPassedAway: Boolean
  preferredLanguage: String @uuidOrEnum(enum: ["PreferredLanguageType"])
  identification: IdentificationType
  identificationNumber: String
  identificationIssueCity: String
  identificationIssueDate: Date
  identificationExpirationDate: Date
  preferredTitlePrefix: String @uuidOrEnum(enum: ["PreferredTitlePrefixType"])
  preferredTitleSuffix: String @uuidOrEnum(enum: ["PreferredTitleSuffixType"])
  preferredLetterSalutation: String @uuidOrEnum(enum: ["preferredLetterSalutationType"])
  preferredTitleInformation: String
  identificationNumbers: [CrmIdentificationNumberInput!]
  status: CrmStatus
}

extend type Mutation {
  createCrm(input: CreateCrmInput!): CrmGeneral! @auth
  updateCrmGeneral(input: UpdateCrmGeneralInput!): CrmGeneral @auth
}

extend type Query {
  getCrmGeneral(id: ID!): CrmGeneral @auth
}