type CrmListItem {
  id: ID!
  type: CrmType!
  firstName: String
  insertion: String
  lastName: String
  phoneNumber: String
  email: String
  avatar: File
  status: CrmStatus
}

type CrmListSearchResult {
  metadata: SearchMetadata
  items: [CrmListItem!]
}

input ListCrmFilters {
  city: String
  type: CrmType
  status: CrmStatus
}

extend type Query {
  crmList(filters: ListCrmFilters, pagination: Pagination, sort: [Sort!]): CrmListSearchResult! @auth
}
