enum PreferredLanguageType {
  Dutch,
  English,
  Polish,
  German,
  French,
  Italian,
  Spanish,
  Portuguese
}

enum PreferredTitlePrefixType {
  Dr,
  Mr,
  Ir,
  Ing,
  Drs
}

enum PreferredTitleSuffixType {
  Msc,
  MA,
  MRE,
  MBA,
  Bc
}

enum PreferredLetterSalutationType {
  Family,
  Lord,
  Mylady,
  LordMylady
}

type CrmGeneral {
  id: ID!
  firstName: String
  extraNames: String
  insertion: String
  lastName: String
  avatar: File
  gender: GenderType
  dateOfBirth: Date
  placeOfBirth: String
  nationality: String
  preferredLanguage: String @uuidOrEnum(enum: ["PreferredLanguageType"])
  identification: String
  identificationNumber: String
  identificationIssueCity: String
  identificationIssueDate: Date
  preferredTitlePrefix: String @uuidOrEnum(enum: ["PreferredTitlePrefixType"])
  preferredTitleSuffix: String @uuidOrEnum(enum: ["PreferredTitleSuffixType"])
  preferredLetterSalutation: String @uuidOrEnum(enum: ["preferredLetterSalutationType"])
  preferredTitleInformation: String
  identificationNumbers: [CrmIdentificationNumber!]
}

type CrmIdentificationNumber {
  id: ID!
  type: String!
  number: String!
}

input CrmIdentificationNumberInput {
  type: String!
  number: String!
}

input CreateCrmInput {
  firstName: String
  extraNames: String
  insertion: String
  lastName: String
  gender: GenderType
}

input UpdateCrmGeneralInput {
  id: ID!
  firstName: String
  extraNames: String
  insertion: String
  lastName: String
  gender: GenderType
  avatarId: String,
  dateOfBirth: Date
  placeOfBirth: String
  nationality: String
  preferredLanguage: String @uuidOrEnum(enum: ["PreferredLanguageType"])
  identification: String
  identificationNumber: String
  identificationIssueCity: String
  identificationIssueDate: Date
  preferredTitlePrefix: String @uuidOrEnum(enum: ["PreferredTitlePrefixType"])
  preferredTitleSuffix: String @uuidOrEnum(enum: ["PreferredTitleSuffixType"])
  preferredLetterSalutation: String @uuidOrEnum(enum: ["preferredLetterSalutationType"])
  preferredTitleInformation: String
  identificationNumbers: [CrmIdentificationNumberInput!]
}

extend type Mutation {
  createCrm(input: CreateCrmInput!): CrmGeneral! @auth
  updateCrmGeneral(input: UpdateCrmGeneralInput!): CrmGeneral @auth
}

extend type Query {
  getCrmGeneral(id: ID!): CrmGeneral @auth
}