enum DmsEntityType {
    Pim
    Ncp
    Crm
    Sales
}

enum DmsFolderType {
    Custom
    Default
}

enum DmsPimFolderType {
    Aquisition
    Quotation
    SalesOrder
    Property
    Drawing
    Questionaires
    ListOfItems
    Publication
    Contracts
    Internal
}

enum DmsCrmFolderType {
    Personal
    Emails
    ContractsPrint
    Surveys
    Invoices
}

enum DmsFolderViewType {
    Emails
    File
    Questionaires
    ListOfItems
    Contracts
    Surveys
    Invoices
}

type DmsFolder {
    entityId: ID!
    id: ID!
    companyId: ID!
    foldername: String!
    entityType: DmsEntityType!
    type: DmsFolderType!
    order: Int
    deletedAt: Date
    isEmailFolder: Boolean
    viewType: DmsFolderViewType!
    filesCount: Int
}

input CreateDmsFolderInput {
    entityId: ID!
    foldername: String!
    entityType: DmsEntityType!
    type: DmsFolderType!
    order: Int
    deletedAt: Date
}

input UpdateDmsFolderInput {
    entityId: ID!
    id: ID!
    foldername: String!
    entityType: DmsEntityType!
    type: DmsFolderType!
    order: Int
    deletedAt: Date
}

input DeleteDmsFolderInput {
    entityId: ID!
    id: ID!
}

extend type Mutation {
    createDmsFolder(input: CreateDmsFolderInput!): DmsFolder! @auth
    updateDmsFolder(input: UpdateDmsFolderInput!): DmsFolder! @auth
    deleteDmsFolder(input: DeleteDmsFolderInput!): Boolean! @auth
}

extend type Query {
    listDmsFolders(entityId: ID!, withFileAmount: Boolean): [DmsFolder!] @auth
    getDmsFolder(folderId: ID!): DmsFolder @auth
}
