type EmailAndName {
    email: String!
    name: String!
}

input EmailAndNameInput {
    email: String!
    name: String!
}

type EmailFolder {
    id: ID!
    name: String!
    displayName: String
}

type EmailListItem {
    id: ID!
    folder: EmailFolder!
    from: [EmailAndName!]!
    to: [EmailAndName!]!
    subject: String!
    date: Date!
    unread: Boolean
}

type Email {
    id: ID!
    folder: EmailFolder!
    from: [EmailAndName!]!
    to: [EmailAndName!]!
    cc: [EmailAndName!]
    bcc: [EmailAndName!]
    subject: String!
    body: String!
    date: Date!
    unread: Boolean
}

type EmailFolderListItem {
    folder: EmailFolder!
    numberOfUnreadEmails: Int!
}

input SendEmailInput {
    to: [EmailAndNameInput!]!
    cc: [EmailAndNameInput!]
    bcc: [EmailAndNameInput!]
    subject: String!
    body: String!
}

input UpdateEmailInput {
    id: ID!
    unread: Boolean
}

extend type Mutation {
    sendEmail(input: SendEmailInput!): Boolean! @auth
    updateEmail(input: UpdateEmailInput!): Email @auth
}

extend type Query {
    listEmailFolders: [EmailFolderListItem!] @auth
    listEmail(folderId: ID!): [EmailListItem!] @auth
    getEmail(id: ID!): Email @auth
}