enum IdentificationNumberType {
  Sap,
  Form
}

type IdentificationNumber {
  id: String!
  name: String
  number: String
  type: String @uuidOrEnum(enum: ["IdentificationNumberType"])
  dateCreated: Date
}

input AddIdentificationNumberInput {
  pimId: String!
  name: String
  type: String @uuidOrEnum(enum: ["IdentificationNumberType"])
}

input UpdateIdentificationNumberInput {
  pimId: String!
  id: String!
  name: String
  number: String
  type: String @uuidOrEnum(enum: ["IdentificationNumberType"])
}
