type NcpServices implements LastUpdated & Services {
  id: ID!
  hotWaterSupplies: [Service!]
  heatingSources: [Service!]
  additionalServices: [Service!]
  dateUpdated: Date
  lastEditedBy: LastUpdatedProfile
  servicesDescription: String
}

extend type Query {
  getNcpServices(id: ID!): NcpServices!
}

type NcpWithNewService  {
  ncp: NcpServices!
  newService: Service!
}

extend type Mutation {
  addNcpService(input: AddServiceInput!): NcpWithNewService! @auth
  updateNcpService(input: UpdateServiceInput!): NcpServices! @auth
  updateNcpServiceDescription(input: ServiceDescriptionInput!): NcpServices! @auth
}
