extend type Mutation {
  addNcpLabel(input: LabelInput!): Label! @auth
  removeNcpLabel(id: ID!): Boolean! @auth
}

extend type Query {
  getNcpLabels(parentId: ID!, properties: [LabelProperty!]): [Label!] @auth
}
