type NcpLinkedPims implements EntityLinkedWithPims {
  id: ID!
  dateUpdated: Date
  lastEditedBy: Profile
  linkedProperties(filters: LinkedPimFilters, sort: [Sort!], pagination: Pagination!): PimListSearchResult! @auth
  linkedPropertiesIds: [ID!]
  description: String
}

extend type Mutation {
  setNcpLinkedPims(input: SetLinkedPimsInput!): NcpLinkedPims! @auth
  updateNcpLinkedPropertiesListDescription(input: UpdateLinkedPropertiesListDescription!): NcpGeneral @auth
}

extend type Query {
  getNcpLinkedPims(id: ID!): NcpLinkedPims! @auth
}
