input NcpCharacteristicsInput {
  id: ID!
  projectMarketing: ProjectMarketingInput
  measurements: MeasurementsInput
  energy: EnergyInput
  accountManagersIds: [ID!]
  attentionNote: String
  invoiceDetails: InvoiceDetailsInput
  characteristicsDescription: String
}

type NcpCharacteristics implements LastUpdated & HasCharacteristicsSections {
  id: ID!
  characteristicsSections: [CharacteristicsSections!]
  projectMarketing: ProjectMarketing
  measurements: Measurements
  energy: Energy
  accountManagers: [Profile!]
  accountManagersIds: [ID!]
  identificationNumbers: [IdentificationNumber!]
  attentionNote: String
  invoiceDetails: InvoiceDetails
  lastEditedBy: LastUpdatedProfile
  dateUpdated: Date
  characteristicsDescription: String
}

type NcpWithNewIdentificationNumber {
  ncp: NcpGeneral!
  newIdentificationNumber: IdentificationNumber!
}

extend type Mutation {
  addNcpIdentificationNumber(input: AddIdentificationNumberInput!): NcpCharacteristics! @auth
  setNcpCharacteristics(input: SetCharacteristicsSectionsInput!): NcpCharacteristics! @auth
  updateNcpCharacteristics(input: NcpCharacteristicsInput!): NcpCharacteristics! @auth
}

extend type Query {
  getNcpCharacteristics(id: ID!): NcpCharacteristics! @auth
}
