enum NcpType {
  Houses,
  Apartments,
  BuildingPlots
}

enum ProjectType {
    Commercial,
    Relet,
    NewConstruction,
}

enum ProgressStatus {
  Concept,
  InPreparation,
  InPresale,
  InProgress,
  Delivered,
}

enum ProjectRisk {
  Low,
  Middle,
  High
}

input CreateNcpInput {
  type: NcpType!
  name: String!
  additionalName: String
  street: String!
  houseNumber: String!
  zipCode: String!
  city: String!
  country: String!
  additionalHouseNumber: String
  projectType: ProjectType
}

input UpdateNcpInput {
  id: ID!
  name: String!
  additionalName: String
  street: String!
  houseNumber: String!
  additionalHouseNumber: String
  zipCode: String!
  city: String!
  country: String!
  automaticallyCalculateQuantity: Boolean
  objectTypesCount: Int
  properties: Int
  progressStatus: ProgressStatus
  startConstruction: Date
  noteStartConstruction: String
  startSale: Date
  noteStartSale: String
  startDelivery: Date
  noteStartDelivery: String
  startConstructionAfterPresalePercentage: Int
  projectRisk: ProjectRisk
  notes: String
  projectType: ProjectType
}

type NcpGeneral implements LastUpdated {
  id: ID!
  type: NcpType!
  dateCreated: Date
  dateUpdated: Date
  lastEditedBy: LastUpdatedProfile
  name: String!
  additionalName: String
  street: String!
  houseNumber: String!
  additionalHouseNumber: String
  zipCode: String!
  city: String!
  country: String!
  archived: Boolean!
  automaticallyCalculateQuantity: Boolean
  properties: Int
  objectTypesCount: Int
  progressStatus: ProgressStatus
  startConstruction: Date
  noteStartConstruction: String
  startSale: Date
  noteStartSale: String
  startDelivery: Date
  noteStartDelivery: String
  startConstructionAfterPresalePercentage: Int
  projectRisk: ProjectRisk
  notes: String
  objectTypesListDescription: String
  objectTypesListLastUpdatedBy: Profile
  objectTypesListLastUpdatedOn: Date
  linkedPropertiesListDescription: String
  linkedPropertiesListLastUpdatedBy: Profile
  linkedPropertiesListLastUpdatedOn: Date
  projectType: ProjectType
}

type NcpSearchResult {
  metadata: SearchMetadata
  items: [NcpGeneral!]
}

input NcpWithSameAddressInput {
  ncpId: String
  street: String
  houseNumber: String
  zipCode: String
  city: String
}

extend type Query {
  getNcp(id: ID!): NcpGeneral! @auth
  getNcpWithSameAddress(input: NcpWithSameAddressInput!): NcpSearchResult! @auth
}

extend type Mutation {
  createNcp(input: CreateNcpInput!): NcpGeneral! @auth
  updateNcp(input: UpdateNcpInput!): NcpGeneral! @auth
}
