type PimMedia implements LastUpdated {
  id: String!
  pictures(sort: Sort): [Picture!]
  mainPictureId: String
  mediaLinks: [MediaLink!]
  textChapters: [TextChapter!]
  usps: [Usp!]
  tags: [Tag!]
  dateUpdated: Date
  lastEditedBy: Profile
  description: String
}

type PimWithNewPictures {
  pim: Pim!
  newPictures: [Picture!]
}

type PimWithNewTextChapter {
  pim: Pim!
  newChapter: TextChapter!
}

type PimWithNewUsp {
  pim: Pim!
  newUsp: Usp!
}

type PimWithNewMediaLink {
  pim: Pim!
  newMediaLink: MediaLink!
}

type PimWithNewTag {
  pim: Pim!
  newTag: Tag!
}

input NewPictureInput {
  fileID: String!
}

input AddPicturesInput {
  pimId: String!
  pictures: [NewPictureInput!]!
}

input AddTextChapterInput {
  pimId: String!
  name: String
  type: String @uuidOrEnum(enum: ["ChapterOrUspType"])
  text: String
}

input UpdateTextChapterInput {
  pimId: String!
  id: String!
  name: String
  type: String @uuidOrEnum(enum: ["ChapterOrUspType"])
  text: String
}

input AddUspInput {
  pimId: String!
  type: String @uuidOrEnum(enum: ["ChapterOrUspType"])
  description: String
}

input UpdateUspInput {
  pimId: String!
  id: String!
  type: String @uuidOrEnum(enum: ["ChapterOrUspType"])
  description: String,
  name: String
}

input AddMediaLinkInput {
  pimId: String!
  type: String @uuidOrEnum(enum: ["MediaLinkType"])
  url: String
  name: String
}

input UpdateMediaLinkInput {
  pimId: String!
  id: String!
  type: String @uuidOrEnum(enum: ["MediaLinkType"])
  url: String
  name: String
}

input AddTagInput {
  pimId: String!
  type: String @uuidOrEnum(enum: ["TagType"])
  description: String
  name: String
}

input UpdateTagInput {
  pimId: String!
  id: String!
  type: String @uuidOrEnum(enum: ["TagType"])
  description: String
  name: String
}

input UpdatePictureInput {
  pimId: String!
  id: String!
  type: String @uuidOrEnum(enum: ["PictureType"])
  name: String
  description: String
  fileId: String
}

extend type Query {
  getPimMedia(id: ID!): PimMedia! @auth
}

extend type Mutation {
  addPictures(input: AddPicturesInput!): PimWithNewPictures @auth
  updatePicture(input: UpdatePictureInput!): Pim @auth
  addTextChapter(input: AddTextChapterInput!): PimWithNewTextChapter @auth
  updateTextChapter(input: UpdateTextChapterInput!): Pim @auth
  addUsp(input: AddUspInput!): PimWithNewUsp @auth
  updateUsp(input: UpdateUspInput!): Pim @auth
  addMediaLink(input: AddMediaLinkInput!): PimWithNewMediaLink @auth
  updateMediaLink(input: UpdateMediaLinkInput!): Pim @auth
  addTag(input: AddTagInput!): PimWithNewTag @auth
  updateTag(input: UpdateTagInput!): Pim @auth
}
