type PimMeters implements LastUpdated {
  id: String!
  meters: [Meter!]
  metersMeta: MetersMeta
  dateUpdated: Date
  lastEditedBy: Profile
}

extend type Query {
  getPimMeters(id: ID!): PimMeters! @auth
}

extend type Mutation {
  addPimReading(input: AddReadingInput!): Pim @auth
  updatePimReading(input: UpdateReadingInput!): Pim @auth
  addPimMeter(input: AddMeterInput!): Pim @auth
  updatePimMeter(input: UpdateMeterInput!): Pim @auth
}

