input PimGeneralInput {
  id: ID!
  realEstateType: RealEstateType
  street: String!
  houseNumberPrefix: String
  houseNumber: String!
  houseNumberAddition: String
  constructionNumberPrefix: String
  constructionNumber: String
  constructionNumberAddition: String
  postalCode: String!
  district: String
  city: String!
  state: String
  county: String
  country: String!
  developmentType: DevelopmentType
  status: PimStatus
  salePrice: Float
  rentPrice: Float
  description: String
  livingArea: Int
  attention: String
  houseGeneral: HouseGeneralInput
  extraAddress: ExtraAddressInput
  showExtraAddress: Boolean
  showIdentificationNumber: Boolean
}

type PropertyAvailabilityInformation {
  availability: PropertyAvailability
  from: Date
  notes: String
  habitation: PropertyHabitation
  currentUse: String
  currentDestination: String
}

type ConstructionInformation {
  type: ConstructionType
  from: Date
  to: Date
  notes: String
}

type HouseGeneral  {
  availability: PropertyAvailabilityInformation
  construction: ConstructionInformation
  floor: FloorType
  propertyConnection: PropertyConnection
  propertyDetails: PropertyTypeDetailed
}

input PropertyAvailabilityInformationInput {
  availability: PropertyAvailability
  from: Date
  notes: String
  habitation: PropertyHabitation
  currentUse: String
  currentDestination: String
}

input HouseGeneralInput {
  availability: PropertyAvailabilityInformationInput
  construction: ConstructionInformationInput
  floor: FloorType
  propertyConnection: PropertyConnection
  propertyDetails: PropertyTypeDetailed
}

input ConstructionInformationInput {
  type: ConstructionType
  from: Date
  to: Date
  notes: String
}

type ExtraAddress {
  plotNumber: String
  plotNumberAddition: String
  houseNumberStart: String
  houseNumberEnd: String
}

input ExtraAddressInput {
  plotNumber: String
  plotNumberAddition: String
  houseNumberStart: String
  houseNumberEnd: String
}

type PimGeneral implements LastUpdated {
  id: ID!
  realEstateType: RealEstateType!
  street: String!
  houseNumberPrefix: String
  houseNumber: String!
  houseNumberAddition: String
  constructionNumberPrefix: String
  constructionNumber: String
  constructionNumberAddition: String
  postalCode: String!
  district: String
  city: String!
  state: String
  county: String
  country: String!
  developmentType: DevelopmentType!
  status: PimStatus!
  salePrice: Float
  rentPrice: Float
  description: String
  images: [File!]
  livingArea: Int
  propertyType: PropertyType
  attention: String
  completeness: Float!
  archived: Boolean!
  dateCreated: Date!
  dateUpdated: Date
  lastEditedBy: Profile
  houseGeneral: HouseGeneral
  extraAddress: ExtraAddress
  identificationNumbers: [IdentificationNumber!]
  showExtraAddress: Boolean
  showIdentificationNumber: Boolean
}

type PimWithNewIdentificationNumber {
  pim: Pim!
  newIdentificationNumber: IdentificationNumber!
}

type GeneralPimSearchResult {
  metadata: SearchMetadata
  items: [PimGeneral!]
}

input PimWithSameAddressInput {
  pimId: String
  street: String
  houseNumber: String
  postalCode: String
  city: String
}

extend type Mutation {
  updatePimGeneralInfo(input: PimGeneralInput!): Pim! @auth
  addIdentificationNumber(input: AddIdentificationNumberInput!): PimWithNewIdentificationNumber! @auth
  updateIdentificationNumber(input: UpdateIdentificationNumberInput!): Pim! @auth
}

extend type Query {
  getPimGeneral(id: ID!): PimGeneral! @auth
  getPimsGeneralWithSameAddress(input: PimWithSameAddressInput!): GeneralPimSearchResult! @auth
}
