input PimGeneralInput {
  id: ID!
  realEstateType: RealEstateType
  street: String!
  houseNumberPrefix: String
  houseNumber: String!
  houseNumberAddition: String
  constructionNumberPrefix: String
  constructionNumber: String
  constructionNumberAddition: String
  postalCode: String!
  district: String
  city: String!
  state: String
  county: String
  country: String!
  developmentType: DevelopmentType
  status: PimStatus
  salePrice: Float
  rentPrice: Float
  description: String
  livingArea: Int
  houseGeneral: HouseGeneralInput
  bogGeneral: BogGeneralInput
  parkingGeneral: ParkingLotGeneralInput
  aogGeneral: AogGeneralInput
  extraAddress: ExtraAddressInput
  showExtraAddress: Boolean
  showIdentificationNumber: Boolean
  apartmentGeneral: ApartmentGeneralInput
  buildingPlotGeneral: BuildingPlotGeneralInput
  attentionNote: String
  showAttentionNote: Boolean
}

enum ApartmentType {
  OneBedroomApartment,
  TwoBedroomApartment,
  ThreeBedroomApartment,
  FourBedroomApartment,
  FiveBedroomApartment
}

enum SoilType {
  Clay,
  Peat,
  Sand,
  Loam
}

enum CharacteristicsApartment {
  CorridorApartment,
  ServiceApartment,
  NursingApartment,
  CallFloor,
  DormRoom,
  OpenPorch,
  PorchApartment,
  GalleryApartment,
  Mezzanine,
  Penthouse,
  Maisonette,
  UpstairsApartment,
  DownstairsApartment,
  DoubleUpstairsApartment,
  DoubleDownstairsApartment,
}

input ApartmentPropertyDetailsInput {
  groundfloorApartmentStartsOnFloor: Int
  amountOfTotalFloors: Int
  notes: String
  apartmentType: String @uuidOrEnum(enum: ["ApartmentType"])
  characteristicsApartment: String @uuidOrEnum(enum: ["CharacteristicsApartment"])
}

type ApartmentPropertyDetails {
  groundfloorApartmentStartsOnFloor: Int
  amountOfTotalFloors: Int
  notes: String
  apartmentType: String @uuidOrEnum(enum: ["ApartmentType"])
  characteristicsApartment: String @uuidOrEnum(enum: ["CharacteristicsApartment"])
}

type BuildingPlotPropertyDetails {
  plotReadyForConstruction: Boolean
  buildingPlotNumber: Int
  notes: String
  soilType: String @uuidOrEnum(enum: ["SoilType"])
  measurements: RectangleMeasurement
}

input ApartmentGeneralInput {
  availability: PropertyAvailabilityInformationInput
  construction: ConstructionInformationInput
  propertyDetails: ApartmentPropertyDetailsInput
}

input BuildingPlotPropertyDetailsInput {
  plotReadyForConstruction: Boolean
  buildingPlotNumber: Int
  notes: String
  measurements: RectangleMeasurementInput
  soilType: String @uuidOrEnum(enum: ["SoilType"])
}

input BuildingPlotGeneralInput {
  availability: PropertyAvailabilityInformationInput
  construction: ConstructionInformationInput
  propertyDetails: BuildingPlotPropertyDetailsInput
}

type PropertyAvailabilityInformation {
  availability: PropertyAvailability
  from: Date
  notes: String
  habitation: PropertyHabitation
  currentUse: String
  currentDestination: String
}

type ConstructionInformation {
  type: ConstructionType
  from: Date
  to: Date
  notes: String
}

type ApartmentGeneral {
  availability: PropertyAvailabilityInformation
  construction: ConstructionInformation
  propertyDetails: ApartmentPropertyDetails
}

type BuildingPlotGeneral {
  availability: PropertyAvailabilityInformation
  construction: ConstructionInformation
  propertyDetails: BuildingPlotPropertyDetails
}

type HouseGeneral  {
  availability: PropertyAvailabilityInformation
  construction: ConstructionInformation
  floor: FloorType
  propertyConnection: PropertyConnection
  propertyDetails: PropertyTypeDetailed
}

input PropertyAvailabilityInformationInput {
  availability: PropertyAvailability
  from: Date
  notes: String
  habitation: PropertyHabitation
  currentUse: String
  currentDestination: String
}

input HouseGeneralInput {
  availability: PropertyAvailabilityInformationInput
  construction: ConstructionInformationInput
  floor: FloorType
  propertyConnection: PropertyConnection
  propertyDetails: PropertyTypeDetailed
}

input ConstructionInformationInput {
  type: ConstructionType
  from: Date
  to: Date
  notes: String
}

type ExtraAddress {
  plotNumber: String
  plotNumberAddition: String
  houseNumberStart: String
  houseNumberEnd: String
}

input ExtraAddressInput {
  plotNumber: String
  plotNumberAddition: String
  houseNumberStart: String
  houseNumberEnd: String
}

type PimGeneral implements LastUpdated {
  id: ID!
  realEstateType: RealEstateType!
  street: String!
  houseNumberPrefix: String
  houseNumber: String!
  houseNumberAddition: String
  constructionNumberPrefix: String
  constructionNumber: String
  constructionNumberAddition: String
  postalCode: String!
  district: String
  city: String!
  state: String
  county: String
  country: String!
  developmentType: DevelopmentType!
  status: PimStatus!
  salePrice: Float
  rentPrice: Float
  description: String
  images: [File!]
  livingArea: Int
  propertyType: PropertyType!
  attentionNote: String
  showAttentionNote: Boolean
  completeness: Float!
  archived: Boolean!
  dateCreated: Date!
  dateUpdated: Date
  lastEditedBy: Profile
  houseGeneral: HouseGeneral
  bogGeneral: BogGeneral
  parkingGeneral: ParkingLotGeneral
  aogGeneral: AogGeneral
  extraAddress: ExtraAddress
  identificationNumbers: [IdentificationNumber!]
  showExtraAddress: Boolean
  showIdentificationNumber: Boolean
  apartmentGeneral: ApartmentGeneral
  buildingPlotGeneral: BuildingPlotGeneral
}

type PimWithNewIdentificationNumber {
  pim: Pim!
  newIdentificationNumber: IdentificationNumber!
}

type GeneralPimSearchResult {
  metadata: SearchMetadata
  items: [PimGeneral!]
}

input PimWithSameAddressInput {
  pimId: String
  street: String
  houseNumber: String
  postalCode: String
  city: String
}

extend type Mutation {
  updatePimGeneralInfo(input: PimGeneralInput!): Pim! @auth
}

extend type Query {
  getPimGeneral(id: ID!): PimGeneral! @auth
  getPimsGeneralWithSameAddress(input: PimWithSameAddressInput!): GeneralPimSearchResult! @auth
}
