scalar LabelProperty

type PimLabel {
  id: ID!
  icon: String
  text: String!
  property: LabelProperty!
}

input PimLabelInput {
  pimId: ID!
  icon: String
  text: String!
  property: LabelProperty!
}

extend type Mutation {
  addPimLabel(input: PimLabelInput!): Pim! @auth
  removePimLabel(id: ID!): Pim! @auth
}
