type Profile {
  id: String!
  firstName: String
  lastName: String
  email: String
  avatar: String
  teams: [ProfileTeam!]
}

type ProfileTeam {
  id: String!
  name: String
}

type Company {
  id: String!
  teams: [Team!]
  name: String
}

type Team {
  id: String!
  members: [Profile!]
  company: Company!
  name: String
}

type ProfileSearchResult {
  metadata: SearchMetadata
  items: [Profile!]
}

extend type Query {
  me: Profile @auth
  getProfile(id: ID!): Profile @auth
  getMyTeamMembers(pagination: Pagination, search: String): ProfileSearchResult!
}

extend type Mutation {
  deleteUser(id: String): String @auth
}
