type Sales {
  id: String!
  label: SalesLabel!
  status: SalesStatus!
  createdAt: Date!
  updatedAt: Date!
  name: String
  type: SalesType!
  extraInfo: String
  attentionNote: String
  date: Date
}

type SalesStatusChange {
  id: ID!
  cyclusId: ID!
  status: SalesStatus!
  createdAt: Date!
  historyId: ID!
}

type SalesClient {
  id: ID!
  cyclusId: ID!
  crmId: ID!
}

type SalesPim {
  id: ID!
  cyclusId: ID!
  pimId: ID!
}

type SalesAccountContact {
  id: ID!
  cyclusId: ID!
  userId: ID!
  role: SalesRole!
}

type SalesEntity {
  cyclusId: ID!
  entityType: Entities!
  entityId: ID!
}

type SalesFile {
  cyclusId: ID!
  documentId: ID!
  label: String!
}

type SalesPackage {
  cyclusId: ID!
  package: String!
}

type SalesAddress {
  cyclusId: ID!
  country: String!
  city: String!
  zipCode: String!
  street: String!
  houseNumber: String!
  extraInfo: String
}

type SalesBrokerage {
  cyclusId: ID!
  type: SalesBrokerageType!
  percentage: Int
  fixedAmount: Int
  amountValues: String
  vatPercentage: Int
  reservationRate: String
  partialCommission: Int
  bonusPercentage: Int
  description: String
  notes: String
}

type CreateSales {
  label: SalesLabel!
  type: SalesType!
  extraInfo: String
}

type UpdateSales {
  attentionNote: String
  status: SalesStatus
  date: Date
  type: SalesType
  extraInfo: String
}

type CreateSalesStatusChange {
  cyclusId: ID!
  label: SalesLabel!
  status: SalesStatus!
  historyId: ID!
}

type CreateSalesAccountContact {
  cyclusId: ID!
  userId: ID!
  role: SalesRole!
}

type UpdateSalesAccountContact {
  cyclusId: ID!
  userId: ID!
  role: SalesRole!
}

type CreateSalesEntity {
  cyclusId: ID!
  entityType: Entities!
  entityId: ID!
}

type CreateSalesFile {
  cyclusId: ID!
  documentId: ID!
  label: String!
}

type CreateSalesPackage {
  cyclusId: ID!
  package: String!
}

type CreateSalesAddress {
  cyclusId: ID!
  country: String
  city: String
  zipCode: String
  street: String
  houseNumber: String
  extraInfo: String
}

type UpdateSalesAddress {
  country: String
  city: String
  zipCode: String
  street: String
  houseNumber: String
  extraInfo: String
}

type CreateSalesBrokerage {
  cyclusId: ID!
  type: Int!
  percentage: Int
  fixedAmount: Int
  amountValues: String
  vatPercentage: Int
  reservationRate: String
  partialCommission: Int
  bonusPercentage: Int
  description: String
  notes: String
}

type UpdateSalesBrokerage {
  type: Int
  percentage: Int
  fixedAmount: Int
  amountValues: String
  vatPercentage: Int
  reservationRate: String
  partialCommission: Int
  bonusPercentage: Int
  description: String
  notes: String
}

type CreateSalesPim {
  cyclusId: ID!
  pimId: ID!
}

type BulkCreateSalesPim {
  cyclusId: ID!
  pimIds: [ID!]
}

type CreateSalesCrm {
  cyclusId: ID!
  crmId: ID!
}

type BulkCreateSalesCrm {
  cyclusId: ID!
  crmIds: [ID!]
}

enum SalesBrokerageType {
  Percentage
  Fixed
}

enum SalesLabel {
  Lead
  Acquisition
  Quotation
  Order
  Invoice
}

enum SalesStatus {
  ActionRequired
  Active
  Inactive
  Complete
}

enum SalesType {
  Taxation
  Inspection
  SaleOrder
}

enum SalesRole {
  Accountant
  Concierge
  Gardener
}

input SalesFilters {
  label: SalesLabel!
  status: SalesStatus!
}

type SalesSearchResult {
  metadata: SearchMetadata
  items: [Sales!]
}

input CreateSalesInput {
  label: SalesLabel!
  type: SalesType!
  extraInfo: String
}

extend type Mutation {
  createSales(input: CreateSalesInput!): Sales @auth
}

extend type Query {
  getSalesList(label: SalesLabel!, status: SalesStatus!, sort: [Sort!]): SalesSearchResult @auth
}
