type AdvancedSearchResult {
  users: [Profile!]
  emails: [Profile!]
  crms: [CrmListItem!]
  pims: [Pim!]
  teams: [Team!]
  ncps: [ListNcp!]
  sales: [Sales!]
}

input AdvancedSearchInput {
  keyword: String!
  type: [Entities!]
  page: Int
  size: Int
}

extend type Query {
  advancedSearch(input: AdvancedSearchInput!): AdvancedSearchResult
}
