type SearchResult {
  users: [Profile!]
  emails: [Profile!]
  crms: [CrmListItem!]
  pims: [Pim!]
  teams: [Team!]
  ncps: [ListNcp!]
  sales: [Sales!]
}

input SearchInput {
  keyword: String!
  types: [Entities!]
  page: Int
  size: Int
}

extend type Query {
  search(input: SearchInput!): SearchResult
}
